stages:
- name: Build
  steps:
  - runScriptConfig:
      image: registry.cn-hangzhou.aliyuncs.com/wujianghui/maven:latest
      shellScript: mvn clean package -DskipTests=true
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: wujianghui/restful-api-demo:dev
      registry: registry.cn-hangzhou.aliyuncs.com
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
